services:
  - type: web
    name: yachtcrm
    runtime: docker     # use the Dockerfile in repo root
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:$PORT
      - key: ConnectionStrings__DefaultConnection
        value: Data Source=app.db
      - key: SEED_ON_BOOT
        value: "500"
